"""
Unit tests for Excel Report Generator.
"""
import io
import pytest
from datetime import date
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from openpyxl import load_workbook

from app.db.base import Base
from app.models import Hotel, PriceRecommendations
from app.reports.generator import report_generator


@pytest.fixture
def db_session():
    engine = create_engine("sqlite:///:memory:", echo=False)
    Base.metadata.create_all(bind=engine)
    TestingSession = sessionmaker(bind=engine)
    session = TestingSession()
    try:
        yield session
    finally:
        session.close()


def test_generate_pricing_recommendations_excel(db_session):
    hotel = Hotel(hotel_code="HTL_RPT", hotel_name="Report Hotel", city="Goa")
    db_session.add(hotel)
    db_session.commit()

    stay_dt = date(2026, 10, 20)
    rec = PriceRecommendations(
        hotel_id=hotel.hotel_id,
        room_type_id=1,
        stay_date=stay_dt,
        recommended_rate=6200.0,
        min_rate=4500.0,
        max_rate=8000.0,
        current_rate=5000.0,
        occupancy=78.0,
        forecast_demand=90.0,
        competitor_median=6400.0,
        demand_index=1.24,
        price_reason="High demand",
        confidence_score=0.88,
        status="APPROVED",
    )
    db_session.add(rec)
    db_session.commit()

    excel_bytes = report_generator.generate_pricing_recommendations_excel(
        db_session, hotel_id=hotel.hotel_id, start_date=stay_dt, end_date=stay_dt
    )

    assert isinstance(excel_bytes, bytes)
    assert len(excel_bytes) > 0

    # Verify openpyxl can open generated bytes
    wb = load_workbook(io.BytesIO(excel_bytes))
    ws = wb.active
    assert ws.title == "Pricing Recommendations"
    assert ws.cell(row=1, column=1).value == "Stay Date"
