"""
API routes for Option 5: Executive PDF Reporting & Automated BI Exports.
"""
from typing import List, Optional, Any
from fastapi import APIRouter, Depends, HTTPException, Query, Response, status
from sqlalchemy.orm import Session

from app.db.session import get_db
from app.schemas.reports_bi import (
    ExecutiveScheduleCreate,
    ExecutiveScheduleUpdate,
    ExecutiveScheduleResponse,
    ReportGenerateRequest,
    ReportExportLogResponse,
    BIDatasetExportResponse,
)
from app.services.pdf_bi_report_service import pdf_bi_report_service
from app.api.deps import verify_hotel_access, get_current_user
from app.models.user import User
from app.core.logging import get_logger

logger = get_logger("app.api.v1.pdf_bi_reports")

router = APIRouter(prefix="/hotels/{hotel_id}/executive-reports", tags=["Executive Reports & BI Exports"])


@router.get("/schedules", response_model=List[ExecutiveScheduleResponse])
def get_report_schedules(
    hotel_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Retrieve active email report dispatch schedules."""
    verify_hotel_access(hotel_id, current_user, db)
    return pdf_bi_report_service.get_report_schedules(db, hotel_id)


@router.post("/schedules", response_model=ExecutiveScheduleResponse)
def create_report_schedule(
    hotel_id: int,
    payload: ExecutiveScheduleCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create new automated PDF email dispatch schedule."""
    if payload.hotel_id != hotel_id:
        payload.hotel_id = hotel_id
    return pdf_bi_report_service.create_report_schedule(db, payload)


@router.put("/schedules/{schedule_id}", response_model=ExecutiveScheduleResponse)
def update_report_schedule(
    hotel_id: int,
    schedule_id: int,
    payload: ExecutiveScheduleUpdate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Update an existing automated email dispatch schedule."""
    verify_hotel_access(hotel_id, current_user, db)
    return pdf_bi_report_service.update_report_schedule(
        db, hotel_id, schedule_id, payload.model_dump(exclude_unset=True)
    )


@router.delete("/schedules/{schedule_id}")
def delete_report_schedule(
    hotel_id: int,
    schedule_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Delete an automated email dispatch schedule."""
    verify_hotel_access(hotel_id, current_user, db)
    return pdf_bi_report_service.delete_report_schedule(db, hotel_id, schedule_id)



@router.get("/history", response_model=List[ReportExportLogResponse])
def get_export_history(
    hotel_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Retrieve history log of generated executive PDF reports and BI dataset exports."""
    verify_hotel_access(hotel_id, current_user, db)
    return pdf_bi_report_service.get_export_logs(db, hotel_id)


@router.post("/generate-pdf", response_model=ReportExportLogResponse)
def generate_executive_pdf_report(
    hotel_id: int,
    req: ReportGenerateRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Generate executive PDF revenue briefing with INR pricing (₹) and record in export log."""
    verify_hotel_access(hotel_id, current_user, db)
    if req.hotel_id != hotel_id:
        req.hotel_id = hotel_id
    return pdf_bi_report_service.generate_executive_pdf(db, req)


@router.get("/bi-dataset", response_model=BIDatasetExportResponse)
def get_bi_analytics_dataset(
    hotel_id: int,
    days: int = Query(30, description="Number of historical stay days to export"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Export PowerBI & Tableau compatible JSON/CSV dataset schema."""
    verify_hotel_access(hotel_id, current_user, db)
    return pdf_bi_report_service.export_bi_dataset(db, hotel_id, days=days)


@router.get("/download/{filename}")
def download_report_file(
    hotel_id: int,
    filename: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Simulate file download stream for generated executive PDF report."""
    verify_hotel_access(hotel_id, current_user, db)
    sample_pdf_content = (
        f"%PDF-1.4 Executive Revenue Summary Report for Hotel #{hotel_id}\n"
        f"Generated by Autonomous Revenue AI Agent in INR (₹)\n"
        f"File: {filename}\n"
    )
    return Response(
        content=sample_pdf_content.encode("utf-8"),
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )
